server:
  port: 8080

spring:
  profiles:
    group:
      "default": "local, oauth"  # local, oauth 파일을 포함해서 읽어오라는 뜻
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    개인 서버
#    url: jdbc:mysql://localhost:3306/db_codingrecipe?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: user_codingrecipe
#    password: 1234
     url: ${DB_URL}
     username: ${DB_USERNAME}
     password: ${DB_PASSWORD}
  thymeleaf:
    cache: false
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
